apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Custom Argo CD Project with privileges restricted to Namespace, Pod, Deployment, ConfigMap, StatefulSet, Service, and Ingress

  # Restrict which git repositories applications in this project can pull from
  sourceRepos:
    - 'https://github.com/irajatpandey/argo-cd-learning.git'

  # Restrict target clusters and namespaces
  destinations:
    - namespace: 'default'
      server: 'https://kubernetes.default.svc'
    - namespace: 'dev'
      server: 'https://kubernetes.default.svc'
    - namespace: 'prod'
      server: 'https://kubernetes.default.svc'

  # Cluster-scoped resources whitelist (Namespace)
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  # Namespace-scoped resources whitelist (Pod, Deployment, ConfigMap, StatefulSet, Service, Ingress)
  namespaceResourceWhitelist:
    - group: ''
      kind: Pod
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Service
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'networking.k8s.io'
      kind: Ingress
