apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-waves-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: sync-waves-app
    app.kubernetes.io/component: config
data:
  APP_ENV: {{ .Values.config.env | quote }}
  APP_NAME: {{ .Values.config.appName | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sync-waves-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: sync-waves-app
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
